## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  include:
    - os: osx
      julia: 1.0
      before_script: skip
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
before_script:
  - sudo apt-get -qq update && sudo apt-get install -y python3-pip
  - pip3 install --user pipenv
  - which pipenv

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PyVirtualenv"); Pkg.test("PyVirtualenv"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("PyVirtualenv")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("PyVirtualenv")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
